_index:
    path:     /
    defaults: { _controller: "TravelBundle:Inventory:index" }
    methods:  GET

_show:
    path:     /{id}/show
    defaults: { _controller: "TravelBundle:Inventory:show" }
    methods:  GET

_new:
    path:     /new
    defaults: { _controller: "TravelBundle:Inventory:new" }
    methods:  [GET, POST]

_edit:
    path:     /{id}/edit
    defaults: { _controller: "TravelBundle:Inventory:edit" }
    methods:  [GET, POST]

_delete:
    path:     /{id}/delete
    defaults: { _controller: "TravelBundle:Inventory:delete" }
    methods:  DELETE
