voyage_index:
    path:     /
    defaults: { _controller: "TravelBundle:Voyage:index" }
    methods:  GET

voyage_show:
    path:     /{id}/show
    defaults: { _controller: "TravelBundle:Voyage:show" }
    methods:  GET

voyage_new:
    path:     /new
    defaults: { _controller: "TravelBundle:Voyage:new" }
    methods:  [GET, POST]

voyage_edit:
    path:     /{id}/edit
    defaults: { _controller: "TravelBundle:Voyage:edit" }
    methods:  [GET, POST]

voyage_delete:
    path:     /{id}/delete
    defaults: { _controller: "TravelBundle:Voyage:delete" }
    methods:  DELETE
