<?php

namespace TravelBundle\Repository;

/**
 * InventoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InventoryRepository extends \Doctrine\ORM\EntityRepository
{
	public function findOneByIdJoinedToCategory($inventory)
{
    $query = $this->getDoctrine()
        ->getManager()
        ->createQuery(
        'SELECT p, c FROM TravelBundle:Inventory p
        JOIN p.category c
        WHERE p.type = :id'
    )->setParameter('id', $inventory);

    try {
        return $query->getSingleResult();
    } catch (\Doctrine\ORM\NoResultException $e) {
        return null;
    }
}
}
